export const errorMapping: { [key: string]: string } = {
  'Invalid credentials': 'api.errors.invalidCredentials',
  'Plan not found': 'api.errors.planNotFound',
  'User not found': 'api.errors.userNotFound',
  'Invalid plan ID': 'api.errors.invalidPlanId',
  'This plan is not open for joining': 'api.errors.planClosed',
  'Plan is full, no more participants allowed': 'api.errors.planFull',
  'You are already a participant in this plan': 'api.errors.alreadyParticipant',
  'You do not have permission to update this plan': 'api.errors.noPermission',
  'You do not have permission to add administrators': 'api.errors.noPermissionAddAdmin',
  'User is already an administrator': 'api.errors.alreadyAdmin',
  'Cannot remove the creator as administrator': 'api.errors.cannotRemoveCreator',
  'Missing required fields': 'api.errors.missingFields',
  'Error getting plans': 'api.errors.serverError',
  'Error getting plan': 'api.errors.serverError',
  'Error getting user plans': 'api.errors.serverError',
  'Error abandoning plan': 'api.errors.serverError',
  'Error verifying administrator': 'api.errors.serverError',
  'Invalid or missing token': 'api.errors.invalidOrMissingToken',
  'Username or email already in use': 'api.errors.usernameOrEmailInUse',
  'Password is required': 'api.errors.missingFields',
  'Email is required': 'api.errors.missingFields',
  'Username is required': 'api.errors.missingFields',
  'Invalid email format': 'api.errors.invalidEmailFormat',
  'Password must be at least 6 characters': 'api.errors.passwordTooShort',
  'Passwords do not match': 'api.errors.passwordsDoNotMatch',
  'Error updating user': 'api.errors.serverError',
  'Error fetching user data': 'api.errors.serverError',
  'Error registering user': 'api.errors.serverError',
  'Error logging in': 'api.errors.serverError',
  'Error refreshing token': 'api.errors.serverError',
  'Token not provided': 'api.errors.invalidOrMissingToken',
  'Invalid token': 'api.errors.invalidOrMissingToken'
}; 